### ISSUE TITLE
Final report is not including Failed test cases

### ISSUE THREAD

**Issue by sallojusuresh** [swissmanu/protractor-screenshot-reporter#22]
Yesterday updated my protractor version to 1.6.1 and run the my previously written test cases on latest protractor and observed the following:

1. Failed test cases are not showing on final Report 
2. A blank page has been displayed when open Screenshots(.png) files

Note: It was working fine with my previous protractor version: 1.5.0

Can anyone help me, Thanks in advance

FYI: https://github.com/angular/protractor/issues/1776#

**Comment by swissmanu** [comment]
this repository is about `protractor-screenshot-reporter`, not `protractor-html-screenshot-reporter`.
please consider filling an issue there: https://github.com/jintoppy/protractor-html-screenshot-reporter
